# Generated by Django 3.2.2 on 2021-09-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_lesson_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='pin_teacher',
        ),
    ]
